{"name": "test_contact_us", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.asyncio\n    async def test_contact_us():\n        async with async_playwright() as p:\n            browser = await p.chromium.launch(headless=False)\n            page = await browser.new_page()\n    \n            home_page = HomePage.HomePage(page)\n            await home_page.goto()\n    \n            assert await home_page.is_home_page_visible(), \"Home page title mismatch\"\n    \n            pop_up_page = PopUpPage.PopUpPage(page)\n            await pop_up_page.pop_up()\n            await pop_up_page.pop_up_confirm_button()\n    \n    \n            await home_page.click_contact_us()\n    \n            contact_us_page = ContactUsPage.ContactUsPage(page)\n            assert await contact_us_page.verify_contact_us_page(), \"'GET IN TOUCH' not visible\"\n    \n            await contact_us_page.fill_contact_form(\n                VALID_USER_DATA['name'],\n                VALID_USER_DATA['email'],\n                VALID_USER_DATA['subject'],\n                fake_message\n            )\n    \n            await contact_us_page.upload_file(VALID_USER_DATA['file'])\n    \n            await contact_us_page.click_submit()\n    \n            await contact_us_page.confirm_alert()\n    \n>           assert await contact_us_page.verify_success_message(MESSAGE_DATA['success_message'])\nE           assert False\n\nspec/test/test_Contact_us.py:66: AssertionError"}, "start": 1725989235896, "stop": 1725989242201, "uuid": "844a294e-7750-46b2-b725-a502e713aa5f", "testCaseId": "a253ce36d049ada9983aba692353639e", "fullName": "spec.test.test_Contact_us#test_contact_us"}