{"name": "test_user_login_invalid", "status": "broken", "statusDetails": {"message": "AttributeError: 'SignupPage' object has no attribute 'error_message_visible'. Did you mean: 'error_login_message_visible'?", "trace": "@pytest.mark.asyncio\n    async def test_user_login_invalid():\n        async with async_playwright() as p:\n            browser = await p.chromium.launch(headless=False)\n            page = await browser.new_page()\n    \n            home_page = HomePage.HomePage(page)\n            await home_page.goto()\n    \n            assert await home_page.is_home_page_visible(), \"Home page title mismatch\"\n    \n            pop_up_page = PopUpPage.PopUpPage(page)\n            await pop_up_page.pop_up()\n            await pop_up_page.pop_up_confirm_button()\n    \n    \n            await home_page.click_signup_login()\n            sing_pu_page = SignupPage.SignupPage(page)\n            assert await sing_pu_page.is_login_visible(), \"'Login to your account' is not visible\"\n    \n            await sing_pu_page.logining(EMAIL, PASSWORD)\n            await sing_pu_page.click_login_button()\n    \n>           await sing_pu_page.error_message_visible()\nE           AttributeError: 'SignupPage' object has no attribute 'error_message_visible'. Did you mean: 'error_login_message_visible'?\n\nspec/test/test_Login_invalid.py:38: AttributeError"}, "start": 1725984948246, "stop": 1725984984020, "uuid": "049b738a-dd26-474e-99e1-8d85538486ac", "historyId": "348af597dfafa60919fc15bb06325eb3", "testCaseId": "348af597dfafa60919fc15bb06325eb3", "fullName": "spec.test.test_Login_invalid#test_user_login_invalid", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "spec.test"}, {"name": "suite", "value": "test_Login_invalid"}, {"name": "host", "value": "MacBook-Pro-Aleksandr.local"}, {"name": "thread", "value": "53828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "spec.test.test_Login_invalid"}]}